[package]
name = "fdt_iter"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { version = "7.1.3", default-features = false }
zerocopy = { version = "0.6.1", default-features = false }

[dev-dependencies]
cstr = "0.2.11"
hex-literal = "0.3.4"
