[package]
name = "arceos-loader"
version = "0.1.0"
edition = "2021"

[dependencies]
axstd = { path = "../../ulib/axstd", optional = true }
cpio_reader = "0.1.1"
elf = { version = "0.7.3", default-features = false }
